---
version: 4

type: "internal"

logging:
  max_files: 28
  directory: "logs"

protocol:
  general:
    packets_per_tick: 50
    heartbeat_allowance: 60

  internal:
    token: "Long Discord Token here."

  external:
    host: "0.0.0.0"
    port: 22222

...