---
version: 4

token: "Long Discord Token here."

logging:
  max_files: 28
  directory: "logs"

protocol:
  general:
    packets_per_tick: 50
    heartbeat_allowance: 60

  internal:
    use_plugin_cacert: true

  external:
    host: "0.0.0.0"
    port: 22222

...